### PR TITLE
Karoj/authentication

### PR DESCRIPTION
**Pull request by Karolis11**
Session-based User authorization:
- Sign up
- Log in
- Log out

### CODE REVIEW

**Review by MindaugasJusis — CHANGES_REQUESTED** [review]
When pressing login, and then 'X' to leave the modal, it throws error. I ma adding image lets see if you can open it.
imgimg

**Review by TisIDom — CHANGES_REQUESTED** [review]
I see you've changed the User model, but there's no EF migration. Did the EF migration not commit somehow?

**Comment by edvinaskrupo** [comment]
Domantas left a good point.

Other than that, changes look good, closing the modal no longer produces the error.

**Review by TisIDom — APPROVED** [review]
LGTM!

**Pull request merged**
